# Inspired from https://github.com/marketplace/actions/conda-action
# botched together to include unit testing with unittest
name: unit-testing
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Conda environment
      uses: matthewrmshin/conda-action@v1
      with:
        args: conda env update
    - name: Perform Unit testing
      uses: matthewrmshin/conda-action@v1
      # TODO: as soon as refactoring is done the refactor/ source folder will
      # move to src/. Not sure whether tests should be under refactor or in
      # a different folder...
      with:
        args: pytest refactor/