# Inspired from https://github.com/marketplace/actions/conda-action
# botched together to include unit testing with unittest
jobs:
  unit-test:
    steps:
    - uses: actions/checkout@v1
    - name: Setup Conda environment
      uses: matthewrmshin/conda-action@v1
      with:
        args: conda env update
    - name: Perform Unit testing"
      uses: matthewrmshin/conda-action@v1
      with:
        args: python3 -m unittest tests.dummy